using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Chemistry_Studio
{
    public static class Tokens
    {
        public static Dictionary<string, List<string>> inputTypePredicates;
        public static Dictionary<string, string> outputTypePredicates;
        public static void initializePredSpec()
        {
            inputTypePredicates = new Dictionary<string,List<string>>();
            outputTypePredicates = new Dictionary<string, string>();
            //Initialize input types of predicates
            inputTypePredicates.Add("Max", new List<string>(new string[]{"num"}));
            inputTypePredicates.Add("Min", new List<string>(new string[] { "num" }));
            inputTypePredicates.Add("IE", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Halogen", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("GasAtSTP", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("LiquidAtSTP", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Metalloid", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("NobleGas", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("AlkaliMetal", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("AlkalineEarthMetal", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("RareEarthElement", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("IonicBond", new List<string>(new string[] { "elem" ,"elem"}));
            inputTypePredicates.Add("CovalentBond", new List<string>(new string[] { "elem","elem" }));

            inputTypePredicates.Add("AtomicNumber", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("OxidationState", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Electronegativity", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("ElectronAffinity", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Conductance", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("IonicRadius", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("AtomicRadius", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Group", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Period", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Metallic", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Same", new List<string>(new string[] { "num", "num" }));
            inputTypePredicates.Add("And", new List<string>(new string[] { "bool", "bool" }));
            inputTypePredicates.Add("Or", new List<string>(new string[] { "bool", "bool" }));


            inputTypePredicates.Add("x", new List<string>(new string[] { "null" }));
            //inputTypePredicates.Add("y", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("z", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("h", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("hydrogen", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("he", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("helium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("li", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lithium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("be", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("beryllium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("b", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("boron", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("c", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("carbon", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("n", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("nitrogen", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("o", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("oxygen", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("f", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("fluorine", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ne", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("neon", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("na", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sodium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("mg", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("magnesium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("al", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("aluminium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("si", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("silicon", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("p", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("phosphorus", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("s", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sulfur", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cl", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("chlorine", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("k", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("potassium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ar", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("argon", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ca", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sc", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("scandium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ti", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("titanium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("v", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("vanadium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("chromium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("mn", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("manganese", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("fe", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("iron", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ni", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("nickel", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("co", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cobalt", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cu", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("copper", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("zn", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("zinc", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ga", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("gallium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ge", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("germanium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("as", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("arsenic", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("se", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("selenium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("br", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("bromine", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("kr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("krypton", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rb", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rubidium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("strontium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("y", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("yttrium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("zr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("zirconium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("nb", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("niobium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("mo", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("molybdenum", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tc", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("technetium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ru", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ruthenium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rh", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rhodium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pd", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("palladium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ag", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("silver", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cd", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cadmium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("in", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("indium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sn", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tin", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sb", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("antimony", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("i", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("iodine", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("te", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tellurium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("xe", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("xenon", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cs", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("caesium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ba", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("barium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("la", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lanthanum", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ce", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cerium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("praseodymium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("nd", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("neodymium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pm", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("promethium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sm", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("samarium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("eu", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("europium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("gd", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("gadolinium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tb", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("terbium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("dy", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("dysprosium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ho", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("holmium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("er", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("erbium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tm", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("thulium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("yb", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ytterbium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lu", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lutetium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("hf", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("hafnium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ta", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tantalum", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("w", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tungsten", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("re", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rhenium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("os", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("osmium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ir", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("iridium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pt", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("platinum", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("au", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("gold", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("hg", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("mercury", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tl", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("thallium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pb", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lead", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("bi", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("bismuth", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("at", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("astatine", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("po", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("polonium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rn", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("radon", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("fr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("francium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ra", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("radium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ac", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("actinium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pa", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("protactinium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("th", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("thorium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("np", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("neptunium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("u", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uranium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("am", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("americium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pu", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("plutonium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cm", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("curium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("bk", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("berkelium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cf", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("californium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("es", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("einsteinium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("fm", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("fermium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("md", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("mendelevium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("no", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("nobelium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rf", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rutherfordium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lawrencium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("db", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("dubnium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("bh", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("bohrium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sg", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("seaborgium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("hs", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("hassium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("mt", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("meitnerium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ds", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("darmstadtium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rg", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("roentgenium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uut", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ununtrium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cn", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("copernicium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uup", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ununpentium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uuq", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ununquadium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uuh", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ununhexium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uuo", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ununoctium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uus", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ununseptium", new List<string>(new string[] { "null" }));
            
            //Initialize output types of predicates
            outputTypePredicates.Add("Max", "bool");
            outputTypePredicates.Add("Min", "bool");
            outputTypePredicates.Add("Same", "bool");

            outputTypePredicates.Add("Period", "num");
            outputTypePredicates.Add("Group", "num");
            outputTypePredicates.Add("AtomicNumber", "num");
            outputTypePredicates.Add("OxidationState", "num");
            outputTypePredicates.Add("IonicRadius", "num");
            outputTypePredicates.Add("AtomicRadius", "num");
            outputTypePredicates.Add("IE", "num");
            outputTypePredicates.Add("Metallic", "num");
            outputTypePredicates.Add("Electronegativity", "num");
            outputTypePredicates.Add("ElectronAffinity", "num");
            outputTypePredicates.Add("Conductance", "num");

            outputTypePredicates.Add("Halogen", "bool");
            outputTypePredicates.Add("GasAtSTP", "bool");
            outputTypePredicates.Add("LiquidAtSTP", "bool");
            outputTypePredicates.Add("Metalloid", "bool");
            outputTypePredicates.Add("NobleGas", "bool");
            outputTypePredicates.Add("AlkaliMetal", "bool");
            outputTypePredicates.Add("AlkalineEarthMetal", "bool");
            outputTypePredicates.Add("RareEarthElement", "bool");
            outputTypePredicates.Add("IonicBond", "bool");
            outputTypePredicates.Add("CovalentBond", "bool");
            outputTypePredicates.Add("And", "bool");
            outputTypePredicates.Add("Or", "bool");

            outputTypePredicates.Add("x", "elem");
            //outputTypePredicates.Add("y", "elem");
            outputTypePredicates.Add("z", "elem");
            outputTypePredicates.Add("h", "elem");
            outputTypePredicates.Add("hydrogen", "elem");
            outputTypePredicates.Add("he", "elem");
            outputTypePredicates.Add("helium", "elem");
            outputTypePredicates.Add("li", "elem");
            outputTypePredicates.Add("lithium", "elem");
            outputTypePredicates.Add("be", "elem");
            outputTypePredicates.Add("beryllium", "elem");
            outputTypePredicates.Add("b", "elem");
            outputTypePredicates.Add("boron", "elem");
            outputTypePredicates.Add("c", "elem");
            outputTypePredicates.Add("carbon", "elem");
            outputTypePredicates.Add("n", "elem");
            outputTypePredicates.Add("nitrogen", "elem");
            outputTypePredicates.Add("o", "elem");
            outputTypePredicates.Add("oxygen", "elem");
            outputTypePredicates.Add("f", "elem");
            outputTypePredicates.Add("fluorine", "elem");
            outputTypePredicates.Add("ne", "elem");
            outputTypePredicates.Add("neon", "elem");
            outputTypePredicates.Add("na", "elem");
            outputTypePredicates.Add("sodium", "elem");
            outputTypePredicates.Add("mg", "elem");
            outputTypePredicates.Add("magnesium", "elem");
            outputTypePredicates.Add("al", "elem");
            outputTypePredicates.Add("aluminium", "elem");
            outputTypePredicates.Add("si", "elem");
            outputTypePredicates.Add("silicon", "elem");
            outputTypePredicates.Add("p", "elem");
            outputTypePredicates.Add("phosphorus", "elem");
            outputTypePredicates.Add("s", "elem");
            outputTypePredicates.Add("sulfur", "elem");
            outputTypePredicates.Add("cl", "elem");
            outputTypePredicates.Add("chlorine", "elem");
            outputTypePredicates.Add("k", "elem");
            outputTypePredicates.Add("potassium", "elem");
            outputTypePredicates.Add("ar", "elem");
            outputTypePredicates.Add("argon", "elem");
            outputTypePredicates.Add("ca", "elem");
            outputTypePredicates.Add("sc", "elem");
            outputTypePredicates.Add("scandium", "elem");
            outputTypePredicates.Add("ti", "elem");
            outputTypePredicates.Add("titanium", "elem");
            outputTypePredicates.Add("v", "elem");
            outputTypePredicates.Add("vanadium", "elem");
            outputTypePredicates.Add("cr", "elem");
            outputTypePredicates.Add("chromium", "elem");
            outputTypePredicates.Add("mn", "elem");
            outputTypePredicates.Add("manganese", "elem");
            outputTypePredicates.Add("fe", "elem");
            outputTypePredicates.Add("iron", "elem");
            outputTypePredicates.Add("ni", "elem");
            outputTypePredicates.Add("nickel", "elem");
            outputTypePredicates.Add("co", "elem");
            outputTypePredicates.Add("cobalt", "elem");
            outputTypePredicates.Add("cu", "elem");
            outputTypePredicates.Add("copper", "elem");
            outputTypePredicates.Add("zn", "elem");
            outputTypePredicates.Add("zinc", "elem");
            outputTypePredicates.Add("ga", "elem");
            outputTypePredicates.Add("gallium", "elem");
            outputTypePredicates.Add("ge", "elem");
            outputTypePredicates.Add("germanium", "elem");
            outputTypePredicates.Add("as", "elem");
            outputTypePredicates.Add("arsenic", "elem");
            outputTypePredicates.Add("se", "elem");
            outputTypePredicates.Add("selenium", "elem");
            outputTypePredicates.Add("br", "elem");
            outputTypePredicates.Add("bromine", "elem");
            outputTypePredicates.Add("kr", "elem");
            outputTypePredicates.Add("krypton", "elem");
            outputTypePredicates.Add("rb", "elem");
            outputTypePredicates.Add("rubidium", "elem");
            outputTypePredicates.Add("sr", "elem");
            outputTypePredicates.Add("strontium", "elem");
            outputTypePredicates.Add("y", "elem");
            outputTypePredicates.Add("yttrium", "elem");
            outputTypePredicates.Add("zr", "elem");
            outputTypePredicates.Add("zirconium", "elem");
            outputTypePredicates.Add("nb", "elem");
            outputTypePredicates.Add("niobium", "elem");
            outputTypePredicates.Add("mo", "elem");
            outputTypePredicates.Add("molybdenum", "elem");
            outputTypePredicates.Add("tc", "elem");
            outputTypePredicates.Add("technetium", "elem");
            outputTypePredicates.Add("ru", "elem");
            outputTypePredicates.Add("ruthenium", "elem");
            outputTypePredicates.Add("rh", "elem");
            outputTypePredicates.Add("rhodium", "elem");
            outputTypePredicates.Add("pd", "elem");
            outputTypePredicates.Add("palladium", "elem");
            outputTypePredicates.Add("ag", "elem");
            outputTypePredicates.Add("silver", "elem");
            outputTypePredicates.Add("cd", "elem");
            outputTypePredicates.Add("cadmium", "elem");
            outputTypePredicates.Add("in", "elem");
            outputTypePredicates.Add("indium", "elem");
            outputTypePredicates.Add("sn", "elem");
            outputTypePredicates.Add("tin", "elem");
            outputTypePredicates.Add("sb", "elem");
            outputTypePredicates.Add("antimony", "elem");
            outputTypePredicates.Add("i", "elem");
            outputTypePredicates.Add("iodine", "elem");
            outputTypePredicates.Add("te", "elem");
            outputTypePredicates.Add("tellurium", "elem");
            outputTypePredicates.Add("xe", "elem");
            outputTypePredicates.Add("xenon", "elem");
            outputTypePredicates.Add("cs", "elem");
            outputTypePredicates.Add("caesium", "elem");
            outputTypePredicates.Add("ba", "elem");
            outputTypePredicates.Add("barium", "elem");
            outputTypePredicates.Add("la", "elem");
            outputTypePredicates.Add("lanthanum", "elem");
            outputTypePredicates.Add("ce", "elem");
            outputTypePredicates.Add("cerium", "elem");
            outputTypePredicates.Add("pr", "elem");
            outputTypePredicates.Add("praseodymium", "elem");
            outputTypePredicates.Add("nd", "elem");
            outputTypePredicates.Add("neodymium", "elem");
            outputTypePredicates.Add("pm", "elem");
            outputTypePredicates.Add("promethium", "elem");
            outputTypePredicates.Add("sm", "elem");
            outputTypePredicates.Add("samarium", "elem");
            outputTypePredicates.Add("eu", "elem");
            outputTypePredicates.Add("europium", "elem");
            outputTypePredicates.Add("gd", "elem");
            outputTypePredicates.Add("gadolinium", "elem");
            outputTypePredicates.Add("tb", "elem");
            outputTypePredicates.Add("terbium", "elem");
            outputTypePredicates.Add("dy", "elem");
            outputTypePredicates.Add("dysprosium", "elem");
            outputTypePredicates.Add("ho", "elem");
            outputTypePredicates.Add("holmium", "elem");
            outputTypePredicates.Add("er", "elem");
            outputTypePredicates.Add("erbium", "elem");
            outputTypePredicates.Add("tm", "elem");
            outputTypePredicates.Add("thulium", "elem");
            outputTypePredicates.Add("yb", "elem");
            outputTypePredicates.Add("ytterbium", "elem");
            outputTypePredicates.Add("lu", "elem");
            outputTypePredicates.Add("lutetium", "elem");
            outputTypePredicates.Add("hf", "elem");
            outputTypePredicates.Add("hafnium", "elem");
            outputTypePredicates.Add("ta", "elem");
            outputTypePredicates.Add("tantalum", "elem");
            outputTypePredicates.Add("w", "elem");
            outputTypePredicates.Add("tungsten", "elem");
            outputTypePredicates.Add("re", "elem");
            outputTypePredicates.Add("rhenium", "elem");
            outputTypePredicates.Add("os", "elem");
            outputTypePredicates.Add("osmium", "elem");
            outputTypePredicates.Add("ir", "elem");
            outputTypePredicates.Add("iridium", "elem");
            outputTypePredicates.Add("pt", "elem");
            outputTypePredicates.Add("platinum", "elem");
            outputTypePredicates.Add("au", "elem");
            outputTypePredicates.Add("gold", "elem");
            outputTypePredicates.Add("hg", "elem");
            outputTypePredicates.Add("mercury", "elem");
            outputTypePredicates.Add("tl", "elem");
            outputTypePredicates.Add("thallium", "elem");
            outputTypePredicates.Add("pb", "elem");
            outputTypePredicates.Add("lead", "elem");
            outputTypePredicates.Add("bi", "elem");
            outputTypePredicates.Add("bismuth", "elem");
            outputTypePredicates.Add("at", "elem");
            outputTypePredicates.Add("astatine", "elem");
            outputTypePredicates.Add("po", "elem");
            outputTypePredicates.Add("polonium", "elem");
            outputTypePredicates.Add("rn", "elem");
            outputTypePredicates.Add("radon", "elem");
            outputTypePredicates.Add("fr", "elem");
            outputTypePredicates.Add("francium", "Fr");
            outputTypePredicates.Add("ra", "elem");
            outputTypePredicates.Add("radium", "elem");
            outputTypePredicates.Add("ac", "elem");
            outputTypePredicates.Add("actinium", "elem");
            outputTypePredicates.Add("pa", "elem");
            outputTypePredicates.Add("protactinium", "elem");
            outputTypePredicates.Add("th", "elem");
            outputTypePredicates.Add("thorium", "elem");
            outputTypePredicates.Add("np", "elem");
            outputTypePredicates.Add("neptunium", "elem");
            outputTypePredicates.Add("u", "elem");
            outputTypePredicates.Add("uranium", "elem");
            outputTypePredicates.Add("am", "elem");
            outputTypePredicates.Add("americium", "elem");
            outputTypePredicates.Add("pu", "elem");
            outputTypePredicates.Add("plutonium", "elem");
            outputTypePredicates.Add("cm", "elem");
            outputTypePredicates.Add("curium", "elem");
            outputTypePredicates.Add("bk", "elem");
            outputTypePredicates.Add("berkelium", "elem");
            outputTypePredicates.Add("cf", "elem");
            outputTypePredicates.Add("californium", "elem");
            outputTypePredicates.Add("es", "elem");
            outputTypePredicates.Add("einsteinium", "elem");
            outputTypePredicates.Add("fm", "elem");
            outputTypePredicates.Add("fermium", "elem");
            outputTypePredicates.Add("md", "elem");
            outputTypePredicates.Add("mendelevium", "elem");
            outputTypePredicates.Add("no", "elem");
            outputTypePredicates.Add("nobelium", "elem");
            outputTypePredicates.Add("rf", "elem");
            outputTypePredicates.Add("rutherfordium", "elem");
            outputTypePredicates.Add("lr", "elem");
            outputTypePredicates.Add("lawrencium", "elem");
            outputTypePredicates.Add("db", "elem");
            outputTypePredicates.Add("dubnium", "elem");
            outputTypePredicates.Add("bh", "elem");
            outputTypePredicates.Add("bohrium", "elem");
            outputTypePredicates.Add("sg", "elem");
            outputTypePredicates.Add("seaborgium", "elem");
            outputTypePredicates.Add("hs", "elem");
            outputTypePredicates.Add("hassium", "elem");
            outputTypePredicates.Add("mt", "Mt");
            outputTypePredicates.Add("meitnerium", "elem");
            outputTypePredicates.Add("ds", "Ds");
            outputTypePredicates.Add("darmstadtium", "elem");
            outputTypePredicates.Add("rg", "Rg");
            outputTypePredicates.Add("roentgenium", "elem");
            outputTypePredicates.Add("uut", "Uut");
            outputTypePredicates.Add("ununtrium", "elem");
            outputTypePredicates.Add("cn", "Cn");
            outputTypePredicates.Add("copernicium", "elem");
            outputTypePredicates.Add("uup", "Uup");
            outputTypePredicates.Add("ununpentium", "elem");
            outputTypePredicates.Add("uuq", "Uuq");
            outputTypePredicates.Add("ununquadium", "elem");
            outputTypePredicates.Add("uuh", "Uuh");
            outputTypePredicates.Add("ununhexium", "elem");
            outputTypePredicates.Add("uuo", "Uuo");
            outputTypePredicates.Add("ununoctium", "elem");
            outputTypePredicates.Add("uus", "Uus");
            outputTypePredicates.Add("ununseptium", "elem");
        }

        public static Dictionary<string, string> tokenList;
        public static string[] tList = {"h#H", "hydrogen#H", "he#He", "helium#He", "li#Li", "lithium#Li", "be#Be", "beryllium#Be", "b#B",
          "boron#B", "c#C", "carbon#C", "n#N", "nitrogen#N", "o#O", "oxygen#O", "f#F", "fluorine#F", "ne#Ne", "neon#Ne", "na#Na", "sodium#Na", "mg#Mg",
          "magnesium#Mg", "al#Al", "aluminium#Al", "si#Si", "silicon#Si", "p#P", "phosphorus#P", "s#S", "sulfur#S", "cl#Cl", "chlorine#Cl",
          "k#K", "potassium#K", "ar#Ar", "argon#Ar", "ca#Ca", "calcium#Ca", "sc#Sc", "scandium#Sc", "ti#Ti", "titanium#Ti", "v#V", "vanadium#V",
          "cr#Cr", "chromium#Cr", "mn#Mn", "manganese#Mn", "fe#Fe", "iron#Fe", "ni#Ni", "nickel#Ni", "co#Co", "cobalt#Co", "cu#Cu", "copper#Cu",
          "zn#Zn", "zinc#Zn", "ga#Ga", "gallium#Ga", "ge#Ge", "germanium#Ge", "as#As", "arsenic#As", "se#Se", "selenium#Se", "br#Br", "bromine#Br",
          "kr#Kr", "krypton#Kr", "rb#Rb", "rubidium#Rb", "sr#Sr", "strontium#Sr", "y#Y", "yttrium#Y", "zr#Zr", "zirconium#Zr", "nb#Nb", "niobium#Nb",
          "mo#Mo", "molybdenum#Mo", "tc#Tc", "technetium#Tc", "ru#Ru", "ruthenium#Ru", "rh#Rh", "rhodium#Rh", "pd#Pd", "palladium#Pd", "ag#Ag",
          "silver#Ag", "cd#Cd", "cadmium#Cd", "in#In", "indium#In", "sn#Sn", "tin#Sn", "sb#Sb", "antimony#Sb", "i#I", "iodine#I", "te#Te",
          "tellurium#Te", "xe#Xe", "xenon#Xe", "cs#Cs", "caesium#Cs", "ba#Ba", "barium#Ba", "la#La", "lanthanum#La", "ce#Ce", "cerium#Ce", "pr#Pr",
          "praseodymium#Pr", "nd#Nd", "neodymium#Nd", "pm#Pm", "promethium#Pm", "sm#Sm", "samarium#Sm", "eu#Eu", "europium#Eu", "gd#Gd",
          "gadolinium#Gd", "tb#Tb", "terbium#Tb", "dy#Dy", "dysprosium#Dy", "ho#Ho", "holmium#Ho", "er#Er", "erbium#Er", "tm#Tm", "thulium#Tm",
          "yb#Yb", "ytterbium#Yb", "lu#Lu", "lutetium#Lu", "hf#Hf", "hafnium#Hf", "ta#Ta", "tantalum#Ta", "w#W", "tungsten#W", "re#Re", "rhenium#Re",
          "os#Os", "osmium#Os", "ir#Ir", "iridium#Ir", "pt#Pt", "platinum#Pt", "au#Au", "gold#Au", "hg#Hg", "mercury#Hg", "tl#Tl", "thallium#Tl",
          "pb#Pb", "lead#Pb", "bi#Bi", "bismuth#Bi", "at#At", "astatine#At", "po#Po", "polonium#Po", "rn#Rn", "radon#Rn", "fr#Fr", "francium#Fr",
          "ra#Ra", "radium#Ra", "ac#Ac", "actinium#Ac", "pa#Pa", "protactinium#Pa", "th#Th", "thorium#Th", "np#Np", "neptunium#Np", "u#U", "uranium#U",
          "am#Am", "americium#Am", "pu#Pu", "plutonium#Pu", "cm#Cm", "curium#Cm", "bk#Bk", "berkelium#Bk", "cf#Cf", "californium#Cf", "es#Es",
          "einsteinium#Es", "fm#Fm", "fermium#Fm", "md#Md", "mendelevium#Md", "no#No", "nobelium#No", "rf#Rf", "rutherfordium#Rf", "lr#Lr",
          "lawrencium#Lr", "db#Db", "dubnium#Db", "bh#Bh", "bohrium#Bh", "sg#Sg", "seaborgium#Sg", "hs#Hs", "hassium#Hs", "mt#Mt", "meitnerium#Mt",
          "ds#Ds", "darmstadtium#Ds", "rg#Rg", "roentgenium#Rg", "uut#Uut", "ununtrium#Uut", "cn#Cn", "copernicium#Cn", "uup#Uup", "ununpentium#Uup",
          "uuq#Uuq", "ununquadium#Uuq", "uuh#Uuh", "ununhexium#Uuh", "uuo#Uuo", "ununoctium#Uuo", "uus#Uus", "ununseptium#Uus",
          "alkali metal#AlkaliMetal", "alkaline earth metal#AlkalineEarthMetal", "transition element#transition element",
          "transition metal#transition element", "metalloid#Metalloid", "halogen#Halogen", "noble gas#NobleGas", "inert gas#NobleGas",
          "lanthanide#RareEarthElement", "actinide#RareEarthElement", "gas at stp#GasAtSTP", "liquid at stp#LiquidAtSTP", "ionic bond#IonicBond",
          "covalent#CovalentBond", "spin paired#SpinPaired", "atomic radius#AtomicRadius", "atomic size#AtomicRadius", "ionic radius#IonicRadius",
          "ionic size#IonicRadius", "maximum#Max", "greatest#Max", "most#Max", "highest#Max", "strongest#Max", "best#Max", "smallest#Min",
          "least#Min", "minimum#Min", "lowest#Min", "weakest#Min", "worst#Min", "electronegativity#Electronegativity", "metallic#Metallic",
          "increase#Increase", "decrease#Decrease", "electron affinity#ElectronAffinity", "conductor#Conductance", "quantum number#QuantumNumber",
          "color#Color", "orbital#Orbitals", "family#Family", "oxidation state#OxidationState", "oxidation number#OxidationState",
          "ionization energy#IE", "atomic number#AtomicNumber", "group#Group", "period#Period", "element#x"};

        public static void initialize()
        {
            tokenList = new Dictionary<string, string>();
            foreach (string str in tList)
            {
                string[] temp = str.Split('#');
                tokenList.Add(temp[0], temp[1]);
            }   
        }
    }
}

