using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Chemistry_Studio
{
    static class Tokens
    {
        public static Dictionary<string, List<string>> inputTypePredicates;
        public static Dictionary<string, string> outputTypePredicates;
        public static void initializePredSpec()
        {
            inputTypePredicates = new Dictionary<string,List<string>>();
            outputTypePredicates = new Dictionary<string, string>();
            //Initialize input types of predicates
            inputTypePredicates.Add("Max", new List<string>(new string[]{"num"}));
            inputTypePredicates.Add("Min", new List<string>(new string[] { "num" }));
            inputTypePredicates.Add("IE", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Halogen", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("GasAtSTP", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("LiquidAtSTP", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Metalloid", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("NobleGas", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("AlkaliMetal", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("AlkalineEarthMetal", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("RareEarthElement", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("IonicBond", new List<string>(new string[] { "elem" ,"elem"}));
            inputTypePredicates.Add("CovalentBond", new List<string>(new string[] { "elem","elem" }));

            inputTypePredicates.Add("Electronegativity", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("ElectronAffinity", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Conductance", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("IonicRadius", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("AtomicRadius", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Group", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Period", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Metallic", new List<string>(new string[] { "elem" }));
            inputTypePredicates.Add("Same", new List<string>(new string[] { "num", "num" }));
            inputTypePredicates.Add("And", new List<string>(new string[] { "bool", "bool" }));
            inputTypePredicates.Add("Or", new List<string>(new string[] { "bool", "bool" }));


            inputTypePredicates.Add("x", new List<string>(new string[] { "null" }));
            //inputTypePredicates.Add("y", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("z", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("h", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("hydrogen", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("he", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("helium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("li", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lithium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("be", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("beryllium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("b", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("boron", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("c", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("carbon", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("n", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("nitrogen", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("o", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("oxygen", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("f", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("fluorine", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ne", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("neon", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("na", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sodium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("mg", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("magnesium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("al", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("aluminium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("si", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("silicon", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("p", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("phosphorus", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("s", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sulfur", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cl", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("chlorine", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("k", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("potassium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ar", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("argon", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ca", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sc", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("scandium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ti", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("titanium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("v", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("vanadium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("chromium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("mn", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("manganese", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("fe", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("iron", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ni", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("nickel", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("co", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cobalt", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cu", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("copper", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("zn", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("zinc", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ga", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("gallium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ge", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("germanium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("as", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("arsenic", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("se", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("selenium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("br", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("bromine", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("kr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("krypton", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rb", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rubidium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("strontium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("y", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("yttrium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("zr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("zirconium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("nb", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("niobium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("mo", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("molybdenum", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tc", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("technetium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ru", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ruthenium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rh", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rhodium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pd", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("palladium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ag", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("silver", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cd", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cadmium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("in", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("indium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sn", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tin", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sb", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("antimony", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("i", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("iodine", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("te", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tellurium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("xe", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("xenon", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cs", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("caesium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ba", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("barium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("la", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lanthanum", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ce", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cerium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("praseodymium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("nd", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("neodymium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pm", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("promethium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sm", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("samarium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("eu", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("europium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("gd", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("gadolinium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tb", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("terbium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("dy", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("dysprosium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ho", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("holmium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("er", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("erbium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tm", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("thulium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("yb", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ytterbium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lu", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lutetium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("hf", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("hafnium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ta", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tantalum", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("w", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tungsten", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("re", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rhenium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("os", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("osmium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ir", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("iridium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pt", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("platinum", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("au", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("gold", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("hg", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("mercury", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("tl", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("thallium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pb", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lead", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("bi", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("bismuth", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("at", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("astatine", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("po", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("polonium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rn", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("radon", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("fr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("francium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ra", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("radium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ac", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("actinium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pa", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("protactinium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("th", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("thorium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("np", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("neptunium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("u", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uranium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("am", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("americium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("pu", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("plutonium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cm", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("curium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("bk", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("berkelium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cf", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("californium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("es", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("einsteinium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("fm", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("fermium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("md", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("mendelevium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("no", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("nobelium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rf", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rutherfordium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lr", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("lawrencium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("db", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("dubnium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("bh", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("bohrium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("sg", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("seaborgium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("hs", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("hassium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("mt", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("meitnerium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ds", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("darmstadtium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("rg", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("roentgenium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uut", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ununtrium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("cn", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("copernicium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uup", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ununpentium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uuq", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ununquadium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uuh", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ununhexium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uuo", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ununoctium", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("uus", new List<string>(new string[] { "null" }));
            inputTypePredicates.Add("ununseptium", new List<string>(new string[] { "null" }));
            
            //Initialize output types of predicates
            outputTypePredicates.Add("Max", "null");
            outputTypePredicates.Add("Min", "null");
            outputTypePredicates.Add("Same", "bool");

            outputTypePredicates.Add("Period", "num");
            outputTypePredicates.Add("Group", "num");
            outputTypePredicates.Add("IonicRadius", "num");
            outputTypePredicates.Add("AtomicRadius", "num");
            outputTypePredicates.Add("IE", "num");
            outputTypePredicates.Add("Metallic", "num");
            outputTypePredicates.Add("Electronegativity", "num");
            outputTypePredicates.Add("ElectronAffinity", "num");
            outputTypePredicates.Add("Conductance", "num");

            outputTypePredicates.Add("Halogen", "bool");
            outputTypePredicates.Add("GasAtSTP", "bool");
            outputTypePredicates.Add("LiquidAtSTP", "bool");
            outputTypePredicates.Add("Metalloid", "bool");
            outputTypePredicates.Add("NobleGas", "bool");
            outputTypePredicates.Add("AlkaliMetal", "bool");
            outputTypePredicates.Add("AlkalineEarthMetal", "bool");
            outputTypePredicates.Add("RareEarthElement", "bool");
            outputTypePredicates.Add("IonicBond", "bool");
            outputTypePredicates.Add("CovalentBond", "bool");
            outputTypePredicates.Add("And", "bool");
            outputTypePredicates.Add("Or", "bool");

            outputTypePredicates.Add("x", "elem");
            //outputTypePredicates.Add("y", "elem");
            outputTypePredicates.Add("z", "elem");
            outputTypePredicates.Add("h", "elem");
            outputTypePredicates.Add("hydrogen", "elem");
            outputTypePredicates.Add("he", "elem");
            outputTypePredicates.Add("helium", "elem");
            outputTypePredicates.Add("li", "elem");
            outputTypePredicates.Add("lithium", "elem");
            outputTypePredicates.Add("be", "elem");
            outputTypePredicates.Add("beryllium", "elem");
            outputTypePredicates.Add("b", "elem");
            outputTypePredicates.Add("boron", "elem");
            outputTypePredicates.Add("c", "elem");
            outputTypePredicates.Add("carbon", "elem");
            outputTypePredicates.Add("n", "elem");
            outputTypePredicates.Add("nitrogen", "elem");
            outputTypePredicates.Add("o", "elem");
            outputTypePredicates.Add("oxygen", "elem");
            outputTypePredicates.Add("f", "elem");
            outputTypePredicates.Add("fluorine", "elem");
            outputTypePredicates.Add("ne", "elem");
            outputTypePredicates.Add("neon", "elem");
            outputTypePredicates.Add("na", "elem");
            outputTypePredicates.Add("sodium", "elem");
            outputTypePredicates.Add("mg", "elem");
            outputTypePredicates.Add("magnesium", "elem");
            outputTypePredicates.Add("al", "elem");
            outputTypePredicates.Add("aluminium", "elem");
            outputTypePredicates.Add("si", "elem");
            outputTypePredicates.Add("silicon", "elem");
            outputTypePredicates.Add("p", "elem");
            outputTypePredicates.Add("phosphorus", "elem");
            outputTypePredicates.Add("s", "elem");
            outputTypePredicates.Add("sulfur", "elem");
            outputTypePredicates.Add("cl", "elem");
            outputTypePredicates.Add("chlorine", "elem");
            outputTypePredicates.Add("k", "elem");
            outputTypePredicates.Add("potassium", "elem");
            outputTypePredicates.Add("ar", "elem");
            outputTypePredicates.Add("argon", "elem");
            outputTypePredicates.Add("ca", "elem");
            outputTypePredicates.Add("sc", "elem");
            outputTypePredicates.Add("scandium", "elem");
            outputTypePredicates.Add("ti", "elem");
            outputTypePredicates.Add("titanium", "elem");
            outputTypePredicates.Add("v", "elem");
            outputTypePredicates.Add("vanadium", "elem");
            outputTypePredicates.Add("cr", "elem");
            outputTypePredicates.Add("chromium", "elem");
            outputTypePredicates.Add("mn", "elem");
            outputTypePredicates.Add("manganese", "elem");
            outputTypePredicates.Add("fe", "elem");
            outputTypePredicates.Add("iron", "elem");
            outputTypePredicates.Add("ni", "elem");
            outputTypePredicates.Add("nickel", "elem");
            outputTypePredicates.Add("co", "elem");
            outputTypePredicates.Add("cobalt", "elem");
            outputTypePredicates.Add("cu", "elem");
            outputTypePredicates.Add("copper", "elem");
            outputTypePredicates.Add("zn", "elem");
            outputTypePredicates.Add("zinc", "elem");
            outputTypePredicates.Add("ga", "elem");
            outputTypePredicates.Add("gallium", "elem");
            outputTypePredicates.Add("ge", "elem");
            outputTypePredicates.Add("germanium", "elem");
            outputTypePredicates.Add("as", "elem");
            outputTypePredicates.Add("arsenic", "elem");
            outputTypePredicates.Add("se", "elem");
            outputTypePredicates.Add("selenium", "elem");
            outputTypePredicates.Add("br", "elem");
            outputTypePredicates.Add("bromine", "elem");
            outputTypePredicates.Add("kr", "elem");
            outputTypePredicates.Add("krypton", "elem");
            outputTypePredicates.Add("rb", "elem");
            outputTypePredicates.Add("rubidium", "elem");
            outputTypePredicates.Add("sr", "elem");
            outputTypePredicates.Add("strontium", "elem");
            outputTypePredicates.Add("y", "elem");
            outputTypePredicates.Add("yttrium", "elem");
            outputTypePredicates.Add("zr", "elem");
            outputTypePredicates.Add("zirconium", "elem");
            outputTypePredicates.Add("nb", "elem");
            outputTypePredicates.Add("niobium", "elem");
            outputTypePredicates.Add("mo", "elem");
            outputTypePredicates.Add("molybdenum", "elem");
            outputTypePredicates.Add("tc", "elem");
            outputTypePredicates.Add("technetium", "elem");
            outputTypePredicates.Add("ru", "elem");
            outputTypePredicates.Add("ruthenium", "elem");
            outputTypePredicates.Add("rh", "elem");
            outputTypePredicates.Add("rhodium", "elem");
            outputTypePredicates.Add("pd", "elem");
            outputTypePredicates.Add("palladium", "elem");
            outputTypePredicates.Add("ag", "elem");
            outputTypePredicates.Add("silver", "elem");
            outputTypePredicates.Add("cd", "elem");
            outputTypePredicates.Add("cadmium", "elem");
            outputTypePredicates.Add("in", "elem");
            outputTypePredicates.Add("indium", "elem");
            outputTypePredicates.Add("sn", "elem");
            outputTypePredicates.Add("tin", "elem");
            outputTypePredicates.Add("sb", "elem");
            outputTypePredicates.Add("antimony", "elem");
            outputTypePredicates.Add("i", "elem");
            outputTypePredicates.Add("iodine", "elem");
            outputTypePredicates.Add("te", "elem");
            outputTypePredicates.Add("tellurium", "elem");
            outputTypePredicates.Add("xe", "elem");
            outputTypePredicates.Add("xenon", "elem");
            outputTypePredicates.Add("cs", "elem");
            outputTypePredicates.Add("caesium", "elem");
            outputTypePredicates.Add("ba", "elem");
            outputTypePredicates.Add("barium", "elem");
            outputTypePredicates.Add("la", "elem");
            outputTypePredicates.Add("lanthanum", "elem");
            outputTypePredicates.Add("ce", "elem");
            outputTypePredicates.Add("cerium", "elem");
            outputTypePredicates.Add("pr", "elem");
            outputTypePredicates.Add("praseodymium", "elem");
            outputTypePredicates.Add("nd", "elem");
            outputTypePredicates.Add("neodymium", "elem");
            outputTypePredicates.Add("pm", "elem");
            outputTypePredicates.Add("promethium", "elem");
            outputTypePredicates.Add("sm", "elem");
            outputTypePredicates.Add("samarium", "elem");
            outputTypePredicates.Add("eu", "elem");
            outputTypePredicates.Add("europium", "elem");
            outputTypePredicates.Add("gd", "elem");
            outputTypePredicates.Add("gadolinium", "elem");
            outputTypePredicates.Add("tb", "elem");
            outputTypePredicates.Add("terbium", "elem");
            outputTypePredicates.Add("dy", "elem");
            outputTypePredicates.Add("dysprosium", "elem");
            outputTypePredicates.Add("ho", "elem");
            outputTypePredicates.Add("holmium", "elem");
            outputTypePredicates.Add("er", "elem");
            outputTypePredicates.Add("erbium", "elem");
            outputTypePredicates.Add("tm", "elem");
            outputTypePredicates.Add("thulium", "elem");
            outputTypePredicates.Add("yb", "elem");
            outputTypePredicates.Add("ytterbium", "elem");
            outputTypePredicates.Add("lu", "elem");
            outputTypePredicates.Add("lutetium", "elem");
            outputTypePredicates.Add("hf", "elem");
            outputTypePredicates.Add("hafnium", "elem");
            outputTypePredicates.Add("ta", "elem");
            outputTypePredicates.Add("tantalum", "elem");
            outputTypePredicates.Add("w", "elem");
            outputTypePredicates.Add("tungsten", "elem");
            outputTypePredicates.Add("re", "elem");
            outputTypePredicates.Add("rhenium", "elem");
            outputTypePredicates.Add("os", "elem");
            outputTypePredicates.Add("osmium", "elem");
            outputTypePredicates.Add("ir", "elem");
            outputTypePredicates.Add("iridium", "elem");
            outputTypePredicates.Add("pt", "elem");
            outputTypePredicates.Add("platinum", "elem");
            outputTypePredicates.Add("au", "elem");
            outputTypePredicates.Add("gold", "elem");
            outputTypePredicates.Add("hg", "elem");
            outputTypePredicates.Add("mercury", "elem");
            outputTypePredicates.Add("tl", "elem");
            outputTypePredicates.Add("thallium", "elem");
            outputTypePredicates.Add("pb", "elem");
            outputTypePredicates.Add("lead", "elem");
            outputTypePredicates.Add("bi", "elem");
            outputTypePredicates.Add("bismuth", "elem");
            outputTypePredicates.Add("at", "elem");
            outputTypePredicates.Add("astatine", "elem");
            outputTypePredicates.Add("po", "elem");
            outputTypePredicates.Add("polonium", "elem");
            outputTypePredicates.Add("rn", "elem");
            outputTypePredicates.Add("radon", "elem");
            outputTypePredicates.Add("fr", "elem");
            outputTypePredicates.Add("francium", "Fr");
            outputTypePredicates.Add("ra", "elem");
            outputTypePredicates.Add("radium", "elem");
            outputTypePredicates.Add("ac", "elem");
            outputTypePredicates.Add("actinium", "elem");
            outputTypePredicates.Add("pa", "elem");
            outputTypePredicates.Add("protactinium", "elem");
            outputTypePredicates.Add("th", "elem");
            outputTypePredicates.Add("thorium", "elem");
            outputTypePredicates.Add("np", "elem");
            outputTypePredicates.Add("neptunium", "elem");
            outputTypePredicates.Add("u", "elem");
            outputTypePredicates.Add("uranium", "elem");
            outputTypePredicates.Add("am", "elem");
            outputTypePredicates.Add("americium", "elem");
            outputTypePredicates.Add("pu", "elem");
            outputTypePredicates.Add("plutonium", "elem");
            outputTypePredicates.Add("cm", "elem");
            outputTypePredicates.Add("curium", "elem");
            outputTypePredicates.Add("bk", "elem");
            outputTypePredicates.Add("berkelium", "elem");
            outputTypePredicates.Add("cf", "elem");
            outputTypePredicates.Add("californium", "elem");
            outputTypePredicates.Add("es", "elem");
            outputTypePredicates.Add("einsteinium", "elem");
            outputTypePredicates.Add("fm", "elem");
            outputTypePredicates.Add("fermium", "elem");
            outputTypePredicates.Add("md", "elem");
            outputTypePredicates.Add("mendelevium", "elem");
            outputTypePredicates.Add("no", "elem");
            outputTypePredicates.Add("nobelium", "elem");
            outputTypePredicates.Add("rf", "elem");
            outputTypePredicates.Add("rutherfordium", "elem");
            outputTypePredicates.Add("lr", "elem");
            outputTypePredicates.Add("lawrencium", "elem");
            outputTypePredicates.Add("db", "elem");
            outputTypePredicates.Add("dubnium", "elem");
            outputTypePredicates.Add("bh", "elem");
            outputTypePredicates.Add("bohrium", "elem");
            outputTypePredicates.Add("sg", "elem");
            outputTypePredicates.Add("seaborgium", "elem");
            outputTypePredicates.Add("hs", "elem");
            outputTypePredicates.Add("hassium", "elem");
            outputTypePredicates.Add("mt", "Mt");
            outputTypePredicates.Add("meitnerium", "elem");
            outputTypePredicates.Add("ds", "Ds");
            outputTypePredicates.Add("darmstadtium", "elem");
            outputTypePredicates.Add("rg", "Rg");
            outputTypePredicates.Add("roentgenium", "elem");
            outputTypePredicates.Add("uut", "Uut");
            outputTypePredicates.Add("ununtrium", "elem");
            outputTypePredicates.Add("cn", "Cn");
            outputTypePredicates.Add("copernicium", "elem");
            outputTypePredicates.Add("uup", "Uup");
            outputTypePredicates.Add("ununpentium", "elem");
            outputTypePredicates.Add("uuq", "Uuq");
            outputTypePredicates.Add("ununquadium", "elem");
            outputTypePredicates.Add("uuh", "Uuh");
            outputTypePredicates.Add("ununhexium", "elem");
            outputTypePredicates.Add("uuo", "Uuo");
            outputTypePredicates.Add("ununoctium", "elem");
            outputTypePredicates.Add("uus", "Uus");
            outputTypePredicates.Add("ununseptium", "elem");
        }

        public static Dictionary<string, string> tokenList;
        public static void initialize()
        {
            tokenList = new Dictionary<string, string>();
            tokenList.Add("h", "H");
            tokenList.Add("hydrogen", "H");
            tokenList.Add("he", "He");
            tokenList.Add("helium", "He");
            tokenList.Add("li", "Li");
            tokenList.Add("lithium", "Li");
            tokenList.Add("be", "Be");
            tokenList.Add("beryllium", "Be");
            tokenList.Add("b", "B");
            tokenList.Add("boron", "B");
            tokenList.Add("c", "C");
            tokenList.Add("carbon", "C");
            tokenList.Add("n", "N");
            tokenList.Add("nitrogen", "N");
            tokenList.Add("o", "O");
            tokenList.Add("oxygen", "O");
            tokenList.Add("f", "F");
            tokenList.Add("fluorine", "F");
            tokenList.Add("ne", "Ne");
            tokenList.Add("neon", "Ne");
            tokenList.Add("na", "Na");
            tokenList.Add("sodium", "Na");
            tokenList.Add("mg", "Mg");
            tokenList.Add("magnesium", "Mg");
            tokenList.Add("al", "Al");
            tokenList.Add("aluminium", "Al");
            tokenList.Add("si", "Si");
            tokenList.Add("silicon", "Si");
            tokenList.Add("p", "P");
            tokenList.Add("phosphorus", "P");
            tokenList.Add("s", "S");
            tokenList.Add("sulfur", "S");
            tokenList.Add("cl", "Cl");
            tokenList.Add("chlorine", "Cl");
            tokenList.Add("k", "K");
            tokenList.Add("potassium", "K");
            tokenList.Add("ar", "Ar");
            tokenList.Add("argon", "Ar");
            tokenList.Add("ca", "Ca");
            tokenList.Add("calcium", "Ca");
            tokenList.Add("sc", "Sc");
            tokenList.Add("scandium", "Sc");
            tokenList.Add("ti", "Ti");
            tokenList.Add("titanium", "Ti");
            tokenList.Add("v", "V");
            tokenList.Add("vanadium", "V");
            tokenList.Add("cr", "Cr");
            tokenList.Add("chromium", "Cr");
            tokenList.Add("mn", "Mn");
            tokenList.Add("manganese", "Mn");
            tokenList.Add("fe", "Fe");
            tokenList.Add("iron", "Fe");
            tokenList.Add("ni", "Ni");
            tokenList.Add("nickel", "Ni");
            tokenList.Add("co", "Co");
            tokenList.Add("cobalt", "Co");
            tokenList.Add("cu", "Cu");
            tokenList.Add("copper", "Cu");
            tokenList.Add("zn", "Zn");
            tokenList.Add("zinc", "Zn");
            tokenList.Add("ga", "Ga");
            tokenList.Add("gallium", "Ga");
            tokenList.Add("ge", "Ge");
            tokenList.Add("germanium", "Ge");
            tokenList.Add("as", "As");
            tokenList.Add("arsenic", "As");
            tokenList.Add("se", "Se");
            tokenList.Add("selenium", "Se");
            tokenList.Add("br", "Br");
            tokenList.Add("bromine", "Br");
            tokenList.Add("kr", "Kr");
            tokenList.Add("krypton", "Kr");
            tokenList.Add("rb", "Rb");
            tokenList.Add("rubidium", "Rb");
            tokenList.Add("sr", "Sr");
            tokenList.Add("strontium", "Sr");
            tokenList.Add("y", "Y");
            tokenList.Add("yttrium", "Y");
            tokenList.Add("zr", "Zr");
            tokenList.Add("zirconium", "Zr");
            tokenList.Add("nb", "Nb");
            tokenList.Add("niobium", "Nb");
            tokenList.Add("mo", "Mo");
            tokenList.Add("molybdenum", "Mo");
            tokenList.Add("tc", "Tc");
            tokenList.Add("technetium", "Tc");
            tokenList.Add("ru", "Ru");
            tokenList.Add("ruthenium", "Ru");
            tokenList.Add("rh", "Rh");
            tokenList.Add("rhodium", "Rh");
            tokenList.Add("pd", "Pd");
            tokenList.Add("palladium", "Pd");
            tokenList.Add("ag", "Ag");
            tokenList.Add("silver", "Ag");
            tokenList.Add("cd", "Cd");
            tokenList.Add("cadmium", "Cd");
            tokenList.Add("in", "In");
            tokenList.Add("indium", "In");
            tokenList.Add("sn", "Sn");
            tokenList.Add("tin", "Sn");
            tokenList.Add("sb", "Sb");
            tokenList.Add("antimony", "Sb");
            tokenList.Add("i", "I");
            tokenList.Add("iodine", "I");
            tokenList.Add("te", "Te");
            tokenList.Add("tellurium", "Te");
            tokenList.Add("xe", "Xe");
            tokenList.Add("xenon", "Xe");
            tokenList.Add("cs", "Cs");
            tokenList.Add("caesium", "Cs");
            tokenList.Add("ba", "Ba");
            tokenList.Add("barium", "Ba");
            tokenList.Add("la", "La");
            tokenList.Add("lanthanum", "La");
            tokenList.Add("ce", "Ce");
            tokenList.Add("cerium", "Ce");
            tokenList.Add("pr", "Pr");
            tokenList.Add("praseodymium", "Pr");
            tokenList.Add("nd", "Nd");
            tokenList.Add("neodymium", "Nd");
            tokenList.Add("pm", "Pm");
            tokenList.Add("promethium", "Pm");
            tokenList.Add("sm", "Sm");
            tokenList.Add("samarium", "Sm");
            tokenList.Add("eu", "Eu");
            tokenList.Add("europium", "Eu");
            tokenList.Add("gd", "Gd");
            tokenList.Add("gadolinium", "Gd");
            tokenList.Add("tb", "Tb");
            tokenList.Add("terbium", "Tb");
            tokenList.Add("dy", "Dy");
            tokenList.Add("dysprosium", "Dy");
            tokenList.Add("ho", "Ho");
            tokenList.Add("holmium", "Ho");
            tokenList.Add("er", "Er");
            tokenList.Add("erbium", "Er");
            tokenList.Add("tm", "Tm");
            tokenList.Add("thulium", "Tm");
            tokenList.Add("yb", "Yb");
            tokenList.Add("ytterbium", "Yb");
            tokenList.Add("lu", "Lu");
            tokenList.Add("lutetium", "Lu");
            tokenList.Add("hf", "Hf");
            tokenList.Add("hafnium", "Hf");
            tokenList.Add("ta", "Ta");
            tokenList.Add("tantalum", "Ta");
            tokenList.Add("w", "W");
            tokenList.Add("tungsten", "W");
            tokenList.Add("re", "Re");
            tokenList.Add("rhenium", "Re");
            tokenList.Add("os", "Os");
            tokenList.Add("osmium", "Os");
            tokenList.Add("ir", "Ir");
            tokenList.Add("iridium", "Ir");
            tokenList.Add("pt", "Pt");
            tokenList.Add("platinum", "Pt");
            tokenList.Add("au", "Au");
            tokenList.Add("gold", "Au");
            tokenList.Add("hg", "Hg");
            tokenList.Add("mercury", "Hg");
            tokenList.Add("tl", "Tl");
            tokenList.Add("thallium", "Tl");
            tokenList.Add("pb", "Pb");
            tokenList.Add("lead", "Pb");
            tokenList.Add("bi", "Bi");
            tokenList.Add("bismuth", "Bi");
            tokenList.Add("at", "At");
            tokenList.Add("astatine", "At");
            tokenList.Add("po", "Po");
            tokenList.Add("polonium", "Po");
            tokenList.Add("rn", "Rn");
            tokenList.Add("radon", "Rn");
            tokenList.Add("fr", "Fr");
            tokenList.Add("francium", "Fr");
            tokenList.Add("ra", "Ra");
            tokenList.Add("radium", "Ra");
            tokenList.Add("ac", "Ac");
            tokenList.Add("actinium", "Ac");
            tokenList.Add("pa", "Pa");
            tokenList.Add("protactinium", "Pa");
            tokenList.Add("th", "Th");
            tokenList.Add("thorium", "Th");
            tokenList.Add("np", "Np");
            tokenList.Add("neptunium", "Np");
            tokenList.Add("u", "U");
            tokenList.Add("uranium", "U");
            tokenList.Add("am", "Am");
            tokenList.Add("americium", "Am");
            tokenList.Add("pu", "Pu");
            tokenList.Add("plutonium", "Pu");
            tokenList.Add("cm", "Cm");
            tokenList.Add("curium", "Cm");
            tokenList.Add("bk", "Bk");
            tokenList.Add("berkelium", "Bk");
            tokenList.Add("cf", "Cf");
            tokenList.Add("californium", "Cf");
            tokenList.Add("es", "Es");
            tokenList.Add("einsteinium", "Es");
            tokenList.Add("fm", "Fm");
            tokenList.Add("fermium", "Fm");
            tokenList.Add("md", "Md");
            tokenList.Add("mendelevium", "Md");
            tokenList.Add("no", "No");
            tokenList.Add("nobelium", "No");
            tokenList.Add("rf", "Rf");
            tokenList.Add("rutherfordium", "Rf");
            tokenList.Add("lr", "Lr");
            tokenList.Add("lawrencium", "Lr");
            tokenList.Add("db", "Db");
            tokenList.Add("dubnium", "Db");
            tokenList.Add("bh", "Bh");
            tokenList.Add("bohrium", "Bh");
            tokenList.Add("sg", "Sg");
            tokenList.Add("seaborgium", "Sg");
            tokenList.Add("hs", "Hs");
            tokenList.Add("hassium", "Hs");
            tokenList.Add("mt", "Mt");
            tokenList.Add("meitnerium", "Mt");
            tokenList.Add("ds", "Ds");
            tokenList.Add("darmstadtium", "Ds");
            tokenList.Add("rg", "Rg");
            tokenList.Add("roentgenium", "Rg");
            tokenList.Add("uut", "Uut");
            tokenList.Add("ununtrium", "Uut");
            tokenList.Add("cn", "Cn");
            tokenList.Add("copernicium", "Cn");
            tokenList.Add("uup", "Uup");
            tokenList.Add("ununpentium", "Uup");
            tokenList.Add("uuq", "Uuq");
            tokenList.Add("ununquadium", "Uuq");
            tokenList.Add("uuh", "Uuh");
            tokenList.Add("ununhexium", "Uuh");
            tokenList.Add("uuo", "Uuo");
            tokenList.Add("ununoctium", "Uuo");
            tokenList.Add("uus", "Uus");
            tokenList.Add("ununseptium", "Uus");
            tokenList.Add("alkali metal", "AlkaliMetal");
            tokenList.Add("alkaline earth metal", "AlkalineEarthMetal");
            tokenList.Add("transition element", "transition element");
            tokenList.Add("transition metal", "transition element");
            tokenList.Add("metalloid", "Metalloid");
            tokenList.Add("halogen", "Halogen");
            tokenList.Add("noble gas", "NobleGas");
            tokenList.Add("inert gas", "NobleGas");
            tokenList.Add("lanthanide", "RareEarthElement");
            tokenList.Add("actinide", "RareEarthElement");
            tokenList.Add("gas at stp", "GasAtSTP");
            tokenList.Add("liquid at stp", "LiquidAtSTP");
            tokenList.Add("ionic bond", "IonicBond");
            tokenList.Add("covalent", "CovalentBond");
            tokenList.Add("spin paired", "SpinPaired");
            tokenList.Add("atomic radius", "AtomicRadius");
            tokenList.Add("atomic size", "AtomicRadius");
            tokenList.Add("ionic radius", "IonicRadius");
            tokenList.Add("ionic size", "IonicRadius");
            tokenList.Add("maximum", "Max");
            tokenList.Add("greatest", "Max");
            tokenList.Add("most", "Max");
            tokenList.Add("highest", "Max");
            tokenList.Add("strongest", "Max");
            tokenList.Add("best", "Max");
            tokenList.Add("smallest", "Min");
            tokenList.Add("least", "Min");
            tokenList.Add("minimum", "Min");
            tokenList.Add("lowest", "Min");
            tokenList.Add("weakest", "Min");
            tokenList.Add("worst", "Min");
            tokenList.Add("electronegativity", "Electronegativity");
            tokenList.Add("metallic", "Metallic");
            tokenList.Add("increase", "Increase");
            tokenList.Add("decrease", "Decrease");
            tokenList.Add("electron affinity", "ElectronAffinity");
            tokenList.Add("conductor", "Conductance");
            tokenList.Add("quantum number", "QuantumNumber");
            tokenList.Add("color", "Color");
            tokenList.Add("orbital", "Orbitals");
            tokenList.Add("family", "Family");
            tokenList.Add("oxidation state", "OxidationState");
            tokenList.Add("oxidation number", "OxidationState");
            tokenList.Add("ionization energy", "IE");
            tokenList.Add("atomic number", "AtomicNumber");
            tokenList.Add("group", "Group");
            tokenList.Add("period", "Period");
            tokenList.Add("element", "x");
        }
    }
}

